---
name: 'Release Images'
description: 'Builds images and uploads them to the public registry'
inputs:
  username:
    description: 'User name for the registry'
    required: true
  password:
    description: 'Password for the registry'
    required: true
  image_args:
    description: 'Additional image building arguments'
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Build and release images
      shell: bash
      env:
        QUAY_USERNAME: ${{ inputs.username }}
        QUAY_PASSWORD: ${{ inputs.password }}
      # Pass RELEASE_ARGS on the call, since GITHUB_REF set in the `env` directive doesn't get properly expanded
      run: make release-images RELEASE_ARGS="--tag '${GITHUB_REF##*/}'"
