---
name: Multi-arch builds

on:
  pull_request:

jobs:
  apply-suggestions-commits:
    name: Check the multi-arch builds
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Build the multi-arch images
        run: make multiarch-images
